// Android Manifest 权限速查：常用权限、保护级别与一句它到底能干什么。
// 保护级别按官方口径的四档：普通（装上就有）、危险（要运行时申请）、签名（要同签名）、特殊（要跳系统设置页）。
import type { ReferenceTable } from './reference.ts';

export const ANDROID_PERMISSIONS_TABLE: ReferenceTable = {
	id: 'android-permissions',
	label: 'Android 权限',
	hint: '保护级别 + 用途',
	searchHint: '搜索：camera / 定位 / 危险',
	columns: ['权限', '保护级别', '说明'],
	rows: [
		['INTERNET', '普通', '访问网络。装了就生效，没有它连不上任何网'],
		['ACCESS_NETWORK_STATE', '普通', '读取当前网络连接状态（有没有网、是不是 Wi-Fi）'],
		['ACCESS_WIFI_STATE', '普通', '读取 Wi-Fi 状态与已连网络信息'],
		['CHANGE_WIFI_STATE', '普通', '开关 Wi-Fi、连接指定网络'],
		['CHANGE_NETWORK_STATE', '普通', '开关移动数据等网络连接'],
		['CAMERA', '危险', '拍照与录像（用系统相机 App 拍不需要它，自己调 Camera2 才要）'],
		['RECORD_AUDIO', '危险', '录音'],
		['MODIFY_AUDIO_SETTINGS', '普通', '改音频设置（音量、路由）'],
		['ACCESS_FINE_LOCATION', '危险', '精确位置（GPS 级别）'],
		['ACCESS_COARSE_LOCATION', '危险', '粗略位置（基站 / Wi-Fi 级别）'],
		['ACCESS_BACKGROUND_LOCATION', '危险', '后台也能拿位置（Android 10 起单独申请，审核最严）'],
		['READ_CONTACTS', '危险', '读通讯录'],
		['WRITE_CONTACTS', '危险', '写通讯录'],
		['GET_ACCOUNTS', '危险', '读设备上的账号列表'],
		['READ_CALENDAR', '危险', '读日历事件'],
		['WRITE_CALENDAR', '危险', '写日历事件'],
		['READ_EXTERNAL_STORAGE', '危险', '读共享存储（Android 13 起被细分取代）'],
		['WRITE_EXTERNAL_STORAGE', '危险', '写共享存储（Android 11 起基本失效，改用 MediaStore）'],
		['MANAGE_EXTERNAL_STORAGE', '特殊', '全盘读写（「所有文件访问」，上架要单独说明理由）'],
		['READ_MEDIA_IMAGES', '危险', '读图片（Android 13 起取代读存储）'],
		['READ_MEDIA_VIDEO', '危险', '读视频（Android 13 起）'],
		['READ_MEDIA_AUDIO', '危险', '读音频（Android 13 起）'],
		['READ_MEDIA_VISUAL_USER_SELECTED', '危险', '只读用户选中的图片 / 视频（Android 14 的部分授权）'],
		['READ_PHONE_STATE', '危险', '读手机状态与设备标识（IMEI 在新版本已拿不到）'],
		['READ_PHONE_NUMBERS', '危险', '读本机号码'],
		['CALL_PHONE', '危险', '直接拨号（不弹系统拨号盘）'],
		['ANSWER_PHONE_CALLS', '危险', '接听来电'],
		['READ_CALL_LOG', '危险', '读通话记录'],
		['WRITE_CALL_LOG', '危险', '写通话记录'],
		['SEND_SMS', '危险', '发短信（上架审核极严）'],
		['RECEIVE_SMS', '危险', '收短信（验证码自动填充场景）'],
		['READ_SMS', '危险', '读短信'],
		['RECEIVE_MMS', '危险', '收彩信'],
		['RECEIVE_BOOT_COMPLETED', '普通', '开机自启（配合广播接收器）'],
		['VIBRATE', '普通', '振动'],
		['WAKE_LOCK', '普通', '阻止 CPU 休眠 / 点亮屏幕'],
		['FOREGROUND_SERVICE', '普通', '跑前台服务（Android 14 起还要声明具体类型）'],
		['FOREGROUND_SERVICE_LOCATION', '普通', '前台服务里持续定位（Android 14 起）'],
		['FOREGROUND_SERVICE_CAMERA', '普通', '前台服务里用相机（Android 14 起）'],
		['FOREGROUND_SERVICE_MICROPHONE', '普通', '前台服务里录音（Android 14 起）'],
		['POST_NOTIFICATIONS', '危险', '发通知（Android 13 起要运行时申请，不给就一条都发不出）'],
		['SCHEDULE_EXACT_ALARM', '特殊', '精确闹钟（Android 12 起要用户去设置里开）'],
		['USE_EXACT_ALARM', '普通', '精确闹钟（仅限闹钟 / 日历类应用，无需用户授权）'],
		['BLUETOOTH', '普通', '传统蓝牙（Android 11 及以前）'],
		['BLUETOOTH_ADMIN', '普通', '开关与配对蓝牙（Android 11 及以前）'],
		['BLUETOOTH_CONNECT', '危险', '连接蓝牙设备（Android 12 起）'],
		['BLUETOOTH_SCAN', '危险', '扫描附近蓝牙设备（Android 12 起）'],
		['BLUETOOTH_ADVERTISE', '危险', '对外广播自己（Android 12 起）'],
		['NFC', '普通', '读写 NFC 标签'],
		['BODY_SENSORS', '危险', '读心率等体感数据'],
		['ACTIVITY_RECOGNITION', '危险', '识别走路 / 跑步等活动状态'],
		['USE_BIOMETRIC', '普通', '用指纹 / 人脸做认证（不直接拿生物数据）'],
		['USE_FINGERPRINT', '普通', '老的指纹 API（Android 9 起废弃，改用 USE_BIOMETRIC）'],
		['SYSTEM_ALERT_WINDOW', '特殊', '悬浮窗（「显示在其他应用上层」，要跳设置页开）'],
		['WRITE_SETTINGS', '特殊', '改系统设置（铃声、亮度等）'],
		['REQUEST_INSTALL_PACKAGES', '特殊', '应用内拉起安装包（要跳设置页开）'],
		['REQUEST_IGNORE_BATTERY_OPTIMIZATIONS', '普通', '申请加入电池优化白名单（要跳设置页）'],
		['QUERY_ALL_PACKAGES', '普通', '查询设备上所有已安装应用（商店要求说明用途）'],
		['PACKAGE_USAGE_STATS', '特殊', '读应用使用统计（要用户去设置里授权）'],
		['ACCESS_MEDIA_LOCATION', '危险', '读照片里的地理位置（EXIF）'],
		['SET_WALLPAPER', '普通', '设置壁纸'],
		['EXPAND_STATUS_BAR', '普通', '展开 / 收起状态栏'],
		['INSTALL_SHORTCUT', '普通', '在桌面创建快捷方式'],
		['DISABLE_KEYGUARD', '普通', '在锁屏上显示内容'],
		['HIGH_SAMPLING_RATE_SENSORS', '普通', '以更高频率读传感器（Android 12 起）']
	]
};
