// HTTP 请求头速查：RFC 9110/9111 的请求字段 + CORS / WebSocket / 反向代理 / 前端框架常用的那些。
// 「请求头大全」口径下**以请求方向为主**，个别头（Date、Warning）两个方向都有，说明里点出来。
import type { ReferenceTable } from './reference.ts';

export const HTTP_HEADERS_TABLE: ReferenceTable = {
	id: 'http-headers',
	label: 'HTTP 请求头',
	hint: '标准字段 + 常见非标准',
	searchHint: '搜索：cors / cookie / 缓存',
	columns: ['请求头', '说明', '示例'],
	rows: [
		['Accept', '客户端能接受的响应类型，逗号分隔，可用 q 排优先级', 'text/html,application/json;q=0.9'],
		['Accept-Charset', '能接受的字符集（现代浏览器已不再发）', 'utf-8'],
		['Accept-Encoding', '能接受的压缩方式，服务端据此选 gzip / br', 'gzip, deflate, br'],
		['Accept-Language', '能接受的自然语言，用于内容协商', 'zh-CN,zh;q=0.9,en;q=0.8'],
		['Accept-Datetime', '按时间维度取历史版本（Memento 协议）', 'Thu, 01 Jan 2026 00:00:00 GMT'],
		['Access-Control-Request-Headers', '预检请求：正式请求会带哪些自定义头', 'authorization,content-type'],
		['Access-Control-Request-Method', '预检请求：正式请求会用哪个方法', 'PUT'],
		['Authorization', '身份凭据。Basic 是 base64(账号:密码)，Bearer 后面跟 token', 'Bearer eyJhbGciOi...'],
		['Cache-Control', '缓存指令；请求侧常见 no-cache / no-store / max-age', 'no-cache'],
		['Connection', '连接控制。HTTP/1.1 默认 keep-alive，close 表示用完就断', 'keep-alive'],
		['Content-Encoding', '请求体的压缩方式（与 Accept-Encoding 对应）', 'gzip'],
		['Content-Length', '请求体的字节数；分块传输（chunked）时不能带', '348'],
		['Content-MD5', '请求体内容的 MD5，用于校验完整性（已不推荐）', 'Q2hlY2sgSW50ZWdyaXR5IQ=='],
		[
			'Content-Type',
			'请求体的媒体类型；JSON 要写 application/json 才不触发简单请求',
			'application/json; charset=utf-8'
		],
		['Cookie', '浏览器自动带的 cookie，分号分隔；前端改不了（除 document.cookie）', 'session=abc123; theme=dark'],
		['Date', '发起时间（请求与响应都有；请求侧很少手写）', 'Tue, 22 Sep 2026 02:00:00 GMT'],
		['DNT', 'Do Not Track，值为 1 表示不要跟踪（浏览器已陆续停用）', '1'],
		['Expect', '期望服务端先答复再继续；100-continue 用于大请求体', '100-continue'],
		['Forwarded', '代理链上记录原始协议、主机与客户端地址（X-Forwarded-* 的标准版）', 'for=203.0.113.7;proto=https'],
		['From', '发起请求的用户邮箱（爬虫礼貌地自我介绍用）', 'bot@example.com'],
		['Host', '目标主机与端口，HTTP/1.1 起必填（虚拟主机靠它区分站点）', 'www.toolv.cn:443'],
		['If-Match', '条件请求：ETag 匹配才执行（写操作用它防并发覆盖）', '"33a64df5"'],
		['If-Modified-Since', '条件请求：资源在该时间之后改过才返回 200，否则 304', 'Tue, 15 Sep 2026 10:00:00 GMT'],
		['If-None-Match', '条件请求：ETag 不匹配才返回内容；缓存校验最常用', '"33a64df5"'],
		['If-Range', '断点续传：资源没变才按 Range 返回部分内容', '"33a64df5"'],
		['If-Unmodified-Since', '条件请求：资源在该时间之后没改过才执行', 'Tue, 15 Sep 2026 10:00:00 GMT'],
		['Max-Forwards', '还能被转发几次，用于探测路由环', '10'],
		['Origin', '发起请求的源（协议 + 主机 + 端口），CORS 与 CSRF 校验的依据', 'https://app.example.com'],
		['Pragma', 'HTTP/1.0 时代的缓存控制，等价于 Cache-Control: no-cache', 'no-cache'],
		['Priority', '请求优先级提示（u= 紧急度 0-7，i= 是否可增量处理）', 'u=1, i'],
		['Proxy-Authorization', '对代理服务器的凭据（不是对目标站点）', 'Basic dXNlcjpwYXNz'],
		['Range', '只取部分内容，断点续传与视频拖动靠它', 'bytes=0-1023'],
		['Referer', '来源页地址（拼写错误是历史遗留，一直没改）', 'https://www.toolv.cn/'],
		['Save-Data', '客户端省流模式；服务端可据此降级返回', 'on'],
		['Sec-CH-UA', 'UA 客户端提示：品牌与主版本号，取代 UA 串的位置', '"Chromium";v="128", "Not)A;Brand";v="24"'],
		['Sec-Fetch-Dest', '这请求要拿去干什么：document / image / script / empty(XHR)', 'empty'],
		['Sec-Fetch-Mode', '请求模式：cors / no-cors / same-origin / navigate', 'cors'],
		['Sec-Fetch-Site', '发起方与目标的关系：same-origin / same-site / cross-site', 'same-origin'],
		['Sec-Fetch-User', '这次请求是否由用户触发（点击、回车）', '?1'],
		['Sec-WebSocket-Extensions', 'WebSocket 协商的扩展，如 permessage-deflate 压缩', 'permessage-deflate'],
		['Sec-WebSocket-Key', 'WebSocket 握手的随机串，服务端回它算出的 Accept', 'dGhlIHNhbXBsZSBub25jZQ=='],
		['Sec-WebSocket-Protocol', '子协议协商，服务端从中挑一个', 'graphql-ws'],
		['Sec-WebSocket-Version', 'WebSocket 协议版本，固定 13', '13'],
		['TE', '能接受的传输编码（Transfer-Encoding），常用 trailers', 'trailers'],
		['Trailer', '预告消息末尾会带哪些头（配合分块传输）', 'X-Checksum'],
		['Transfer-Encoding', '请求体的传输编码，chunked 表示分块流式发送', 'chunked'],
		['Upgrade', '请求升级协议，WebSocket 握手就是 Upgrade: websocket', 'websocket'],
		['Upgrade-Insecure-Requests', '浏览器表示「优先给我 https 版本」，值为 1', '1'],
		['User-Agent', '客户端标识串，可被任意伪造，别拿它做安全判断', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)...'],
		['Via', '经过的代理节点列表，用于排查链路', '1.1 vegur'],
		['Warning', '协议升级或缓存异常时的告警（请求与响应都有）', '110 - "Response is Stale"'],
		['X-Api-Key', '非标准：用静态密钥鉴权，很多第三方 API 用它', 'ak_live_9f3c...'],
		['X-CSRF-Token', '非标准：防跨站请求伪造的一次性令牌，需与服务端 cookie 对上', '<token>'],
		['X-Forwarded-For', '非标准：代理链上的客户端 IP（最左通常是最初的客户端）', '203.0.113.7, 198.51.100.2'],
		['X-Forwarded-Host', '非标准：原始请求的 Host，反代改写后保留', 'www.toolv.cn'],
		['X-Forwarded-Proto', '非标准：原始请求的协议，服务端据此决定要不要跳 https', 'https'],
		['X-HTTP-Method-Override', '非标准：用 POST 顶替 PUT / DELETE（老网关只放行 GET/POST）', 'DELETE'],
		['X-Real-IP', '非标准：Nginx 常带的单值客户端 IP（与 X-Forwarded-For 二选一）', '203.0.113.7'],
		['X-Request-ID', '非标准：请求链路 ID，前后端与日志系统串同一条请求', 'b7c3e1d0-5f2a-4c3f-9d0e-1a2b3c4d5e6f'],
		['X-Requested-With', '非标准：jQuery 系 AJAX 会带 XMLHttpRequest，服务端据此识别 XHR', 'XMLHttpRequest']
	]
};
