// 常见端口速查（IANA 的 well-known / registered 端口 + 开发与运维里真会碰到的几个）。
// 只收「填配置、排查占用、写防火墙规则」时会查的：服务端口加一句它到底是干什么的。
import type { ReferenceTable } from './reference.ts';

export const PORTS_TABLE: ReferenceTable = {
	id: 'ports',
	label: '常见端口',
	hint: 'IANA 分配 + 开发运维常遇',
	searchHint: '搜索：3306 / mysql / 数据库',
	columns: ['端口', '服务', '协议', '说明'],
	rows: [
		['20', 'FTP 数据', 'TCP', '文件传输的数据连接（主动模式由服务端发起）'],
		['21', 'FTP 控制', 'TCP', '文件传输的控制连接，明文传账号密码'],
		['22', 'SSH / SFTP', 'TCP', '加密远程登录，也是 scp、git over ssh 的端口'],
		['23', 'Telnet', 'TCP', '明文远程登录，只在调试老设备时用'],
		['25', 'SMTP', 'TCP', '邮件投递（服务器之间）；家宽常被运营商封'],
		['53', 'DNS', 'TCP / UDP', '域名解析；查询走 UDP，大响应与区域传送走 TCP'],
		['67', 'DHCP 服务端', 'UDP', '分配 IP 地址的服务端一侧'],
		['68', 'DHCP 客户端', 'UDP', '申请 IP 的客户端一侧'],
		['69', 'TFTP', 'UDP', '极简文件传输，刷固件、网络引导常用'],
		['80', 'HTTP', 'TCP', '明文网页；浏览器输网址时默认就是这个'],
		['110', 'POP3', 'TCP', '收邮件（把信拉到本地）'],
		['111', 'rpcbind', 'TCP / UDP', 'NFS 等 RPC 服务的端口映射'],
		['123', 'NTP', 'UDP', '时间同步'],
		['135', 'MS RPC', 'TCP', 'Windows 的 RPC 端点映射'],
		['137', 'NetBIOS 名称', 'UDP', 'Windows 局域网名称解析'],
		['138', 'NetBIOS 数据报', 'UDP', 'Windows 局域网浏览'],
		['139', 'NetBIOS 会话', 'TCP', '早期 Windows 文件共享'],
		['143', 'IMAP', 'TCP', '收邮件（邮件留在服务器上，多设备同步）'],
		['161', 'SNMP', 'UDP', '网络设备监控与查询'],
		['162', 'SNMP Trap', 'UDP', '设备主动上报的告警'],
		['179', 'BGP', 'TCP', '自治系统之间的路由交换'],
		['389', 'LDAP', 'TCP / UDP', '目录服务查询（AD 域）'],
		['443', 'HTTPS', 'TCP', 'TLS 加密的网页；HTTP/2 与 HTTP/3（QUIC 走 UDP）也用它'],
		['445', 'SMB', 'TCP', 'Windows 文件共享，勒索软件最常扫的端口之一'],
		['465', 'SMTPS', 'TCP', 'SMTP 直接套 TLS 投递'],
		['514', 'Syslog', 'UDP', '设备与主机的日志上报'],
		['587', 'SMTP 提交', 'TCP', '客户端提交邮件，用 STARTTLS 升级加密'],
		['636', 'LDAPS', 'TCP', 'LDAP over TLS'],
		['873', 'rsync', 'TCP', '增量同步文件'],
		['993', 'IMAPS', 'TCP', 'IMAP over TLS'],
		['995', 'POP3S', 'TCP', 'POP3 over TLS'],
		['1080', 'SOCKS 代理', 'TCP', 'SOCKS4 / SOCKS5 代理'],
		['1194', 'OpenVPN', 'TCP / UDP', 'OpenVPN 默认端口'],
		['1433', 'SQL Server', 'TCP', '微软数据库'],
		['1521', 'Oracle', 'TCP', 'Oracle 数据库监听器'],
		['1701', 'L2TP', 'UDP', 'L2TP VPN'],
		['1723', 'PPTP', 'TCP', 'PPTP VPN，已不安全'],
		['2049', 'NFS', 'TCP / UDP', '网络文件系统'],
		['2181', 'ZooKeeper', 'TCP', '分布式协调，Kafka 依赖它'],
		['2375', 'Docker API', 'TCP', '未加密的 Docker 守护进程，别暴露到公网'],
		['2376', 'Docker API (TLS)', 'TCP', '带 TLS 的 Docker 守护进程'],
		['3000', '开发服务器', 'TCP', 'Node / React / Grafana 等默认端口'],
		['3128', 'Squid 代理', 'TCP', 'HTTP 代理'],
		['3306', 'MySQL / MariaDB', 'TCP', '最常见的关系型数据库端口'],
		['3389', 'RDP', 'TCP', 'Windows 远程桌面，公网暴露会被爆破'],
		['4444', '自定义 / 反弹', 'TCP', 'Metasploit 默认监听；也常被随手当临时端口'],
		['5000', '开发服务器 / Registry', 'TCP', 'Flask、Docker Registry 等默认端口'],
		['5432', 'PostgreSQL', 'TCP', 'PostgreSQL 默认端口'],
		['5601', 'Kibana', 'TCP', 'ELK 的可视化界面'],
		['5672', 'RabbitMQ', 'TCP', 'AMQP 协议端口'],
		['5900', 'VNC', 'TCP', '远程桌面（VNCServer）'],
		['5984', 'CouchDB', 'TCP', '文档数据库 HTTP 接口'],
		['6379', 'Redis', 'TCP', '内存数据库，别裸奔在公网'],
		['6443', 'Kubernetes API', 'TCP', 'kube-apiserver 的默认端口'],
		['7001', 'WebLogic', 'TCP', 'Oracle WebLogic 控制台'],
		['8000', 'HTTP 备用', 'TCP', '开发时最常用的备用 HTTP 端口'],
		['8080', 'HTTP 备用', 'TCP', 'Tomcat、Nginx 代理后端等最常用的一档'],
		['8081', 'HTTP 备用', 'TCP', '常给 Nexus、备用 Web 服务'],
		['8443', 'HTTPS 备用', 'TCP', '8080 的加密版'],
		['8888', '面板 / 笔记本', 'TCP', 'Jupyter Notebook、宝塔面板等'],
		['9000', '应用服务', 'TCP', 'PHP-FPM、Portainer、MinIO 都用它'],
		['9090', '监控 / 面板', 'TCP', 'Prometheus、Cockpit 默认端口'],
		['9092', 'Kafka', 'TCP', 'Kafka broker 对外端口'],
		['9200', 'Elasticsearch', 'TCP', 'REST 接口'],
		['9300', 'Elasticsearch 集群', 'TCP', '节点之间通信'],
		['11211', 'Memcached', 'TCP / UDP', '内存缓存'],
		['15672', 'RabbitMQ 管理台', 'TCP', 'Web 管理界面'],
		['27017', 'MongoDB', 'TCP', 'MongoDB 默认端口']
	]
};
