// User-Agent 对照：把一条 UA 串拆成「哪个片段说明什么」。
// UA 串能任意伪造，这里的用途是**读懂别人发来的串**（排查兼容问题、看爬虫与工具），不是拿来判断人。
import type { ReferenceTable } from './reference.ts';

export const USER_AGENTS_TABLE: ReferenceTable = {
	id: 'user-agents',
	label: 'User-Agent',
	hint: '按片段拆开读',
	searchHint: '搜索：chrome / windows / 爬虫',
	columns: ['UA 片段', '归属', '含义'],
	rows: [
		['Chrome/', '浏览器', '谷歌浏览器，内核 Blink；Edge、Opera、国内浏览器都往里塞这一段'],
		['Chromium/', '浏览器', 'Chrome 的开源上游，某些定制内核用这个'],
		['CriOS/', '浏览器', 'Chrome 的 iOS 版 —— iOS 上只能用 WebKit，所以内核仍是 AppleWebKit'],
		['Edg/', '浏览器', 'Edge 79 起的版本标识（注意结尾没有 e）'],
		['EdgA/', '浏览器', 'Edge 安卓版'],
		['EdgiOS/', '浏览器', 'Edge iOS 版'],
		['Edge/', '浏览器', '老的 EdgeHTML 内核（Windows 10 前期），到 18 为止'],
		['Firefox/', '浏览器', '火狐，内核 Gecko'],
		['FxiOS/', '浏览器', '火狐 iOS 版'],
		['Safari/', '浏览器', '苹果浏览器；这一段的数字是 WebKit 构建号，不是 Safari 版本'],
		['Version/', '浏览器', 'Safari 的真实版本号，看 Safari 版本要读这一段'],
		['OPR/', '浏览器', 'Opera 15 起的标识（换用 Blink 内核之后）'],
		['Opera/', '浏览器', '老的 Opera（Presto 内核），版本停在 12'],
		['MSIE ', '浏览器', 'IE 10 及以前'],
		['Trident/', '渲染引擎', 'IE 11 的内核标识，真实版本看同一串里的 rv:'],
		['rv:11.0', '浏览器', 'IE 11 的真实版本写法'],
		['HeadlessChrome/', '浏览器', '无头 Chrome —— Puppeteer / Playwright 默认就是它'],
		['SamsungBrowser/', '浏览器', '三星自带浏览器'],
		['Electron/', '应用', 'Electron 桌面应用（VS Code、Slack、飞书桌面版都算）'],
		['MicroMessenger/', '国内应用', '微信内置浏览器（公众号网页看这个）'],
		['QQBrowser/', '国内应用', 'QQ 浏览器（PC 端）'],
		['MQQBrowser/', '国内应用', 'QQ 浏览器手机版'],
		['UCBrowser/', '国内应用', 'UC 浏览器'],
		['Quark/', '国内应用', '夸克浏览器'],
		['MiuiBrowser/', '国内应用', '小米浏览器'],
		['HuaweiBrowser/', '国内应用', '华为浏览器'],
		['baiduboxapp/', '国内应用', '百度 App 的 WebView'],
		['AlipayClient/', '国内应用', '支付宝客户端'],
		['DingTalk/', '国内应用', '钉钉客户端'],
		['Weibo/', '国内应用', '微博客户端'],
		['AppleWebKit/', '渲染引擎', 'WebKit 分支；现代浏览器几乎都写它（含 Chrome / Edge）'],
		['Gecko/', '渲染引擎', 'Firefox 的内核'],
		['KHTML, like Gecko', '渲染引擎', '兼容性标记，没有实际含义；WebKit 系普遍照抄'],
		['Windows NT 10.0', '操作系统', 'Windows 10 与 11 —— 两者 UA 完全相同，靠 UA 分不出来'],
		['Windows NT 6.3', '操作系统', 'Windows 8.1'],
		['Windows NT 6.2', '操作系统', 'Windows 8'],
		['Windows NT 6.1', '操作系统', 'Windows 7'],
		['Windows NT 6.0', '操作系统', 'Windows Vista'],
		['Windows NT 5.1', '操作系统', 'Windows XP'],
		['Win64; x64', '操作系统', '64 位 Windows 的声明段'],
		['WOW64', '操作系统', '32 位程序跑在 64 位 Windows 上（Windows on Windows 64）'],
		['Macintosh', '操作系统', 'macOS 桌面的标识段'],
		['Mac OS X', '操作系统', 'macOS；后面的 10_15_7 常被冻结成假版本，不代表真实系统'],
		['CPU iPhone OS', '操作系统', 'iOS 的版本段，例如 17_5 表示 17.5'],
		['CPU OS', '操作系统', 'iPadOS 的版本段（iPadOS 13 起桌面模式会伪装成 Macintosh）'],
		['Android ', '操作系统', '安卓，后面跟版本号，例如 Android 14'],
		['X11', '操作系统', '图形环境标记，桌面 Linux 常见'],
		['CrOS', '操作系统', 'ChromeOS'],
		['Ubuntu', '操作系统', 'Ubuntu 发行版'],
		['Mobile', '设备', '移动设备标记；没有它默认按桌面处理'],
		['Tablet', '设备', '平板设备'],
		['iPhone', '设备', '苹果手机'],
		['iPad', '设备', '苹果平板'],
		['SM-', '设备', '三星机型号前缀，例如 SM-G991B'],
		['Build/', '设备', '安卓机型后面跟的固件号'],
		['Googlebot', '爬虫', 'Google 搜索爬虫'],
		['bingbot', '爬虫', 'Bing 爬虫'],
		['Baiduspider', '爬虫', '百度爬虫'],
		['YandexBot', '爬虫', 'Yandex 爬虫'],
		['curl/', '命令行工具', 'curl，默认就会带自己的名字与版本'],
		['Wget/', '命令行工具', 'wget 下载工具'],
		['PostmanRuntime/', '命令行工具', 'Postman 发出来的请求'],
		['python-requests/', '命令行工具', 'Python requests 库'],
		['axios/', '命令行工具', '前端 axios 库（Node 侧）'],
		['okhttp/', '命令行工具', 'Android / Java 的 OkHttp'],
		['Go-http-client/', '命令行工具', 'Go 标准库的 HTTP 客户端'],
		['node-fetch/', '命令行工具', 'Node 上的 fetch 实现'],
		['Apache-HttpClient/', '命令行工具', 'Java 的 Apache HttpClient'],
		['Java/', '命令行工具', 'Java 自带 HttpURLConnection'],
		['Dalvik/', '运行环境', '安卓的 Dalvik / ART 虚拟机版本段']
	]
};
